### ISSUE TITLE
Store keys as list 

### ISSUE THREAD

**Issue by david8dixon** [sbellus/json-cmake#4]
Would it be possible to store the keys from the following json-formatted data:

{ 
    "foo" : { 
        "key1" : "value1", 
        "key2" : "value2", 
        "key3" : "value3"  
    } 
    "bar" : [ "value1", "value2", "value3"]
} 

such that 

```sbeParseJson(example jsonTest)```
```message( "${example.foo}")``` 

would give:

```key1;key2;key3```

We would like behavior similar to storing a list where:

```
foreach(index IN LISTS example.bar)
  message("${example.bar_${index}}")
endforeach()
```
which would give:

```
value1
value2
value3
```

The major difference being that we can use both the key and the value to do some operation:

```
foreach(key IN LISTS example.foo)
  message("${key} ${example.bar.${key}}")
endforeach()
```
```
key1 value1
key2 value2
key3 value3
```

We are interested in more complex operations than simply printing and we realize that we can have two different key/value json fields where the values are lists, but being able to pair things together as in the third example is less fragile. 

Thanks for your consideration and the tool! We are using it extensively! 

Last comment - any thoughts on how to make the parsing operation more efficient? We are parsing 1000's of json files and it takes on the order of 2-3 minutes.

**Comment by sbellus** [comment]
Hello

It should be not too difficult to provide list of first level keys for json object.

But i miss point in example
foreach(key IN LISTS example.foo)
  message("${key} ${example.bar.${key}}")
endforeach()

${example.bar.key1} has no sense, I guess.

On the other hand you can also write some macro that wraps the result of sbeParseJSON that will give you more usefull variables for you.

**Comment by sbellus** [comment]
Accidentally closed.
Please fell free to comment.

**Comment by sbellus** [comment]
No feedback, closing.
