### ISSUE TITLE
Not works with arrays

### ISSUE THREAD

**Issue by drizt** [sbellus/json-cmake#6]
For 
```json
[1, 5, "aaa"]
```

Output:
```
PARSED = PARSED;0;PARSED_0;1;PARSED_1;2;PARSED_2
0 = 
PARSED_0 = 1
1 = 
PARSED_1 = 5
2 = 
PARSED_2 = aaa
```

**Comment by sbellus** [comment]
Hello

You are right. The parser does not support unnamed values.
The workaround is to use named value

``` cmake
set(jsonTest [=[ "a" : [1, 5, "aaa"] ]=])
sbeParseJson(example jsonTest)

# Now you can use parsed variables.
foreach(var ${example})
    message("${var} = ${${var}}")
endforeach()
```
Then output is
```
example.a = 0;1;2
example.a_0 = 1
example.a_1 = 5
example.a_2 = aaa
```

Is it suitable workaround for you?

**Comment by drizt** [comment]
Actually I don't use json-cmake due very low speed with big json file. I wanted to use json-cmake to parse compile_commands.json. But wrote minimum c application for this purposes in my [PCHLinkTarget](https://github.com/drizt/PCHLinkTarget/blob/master/cmake/parse-compile-commands.c)
 project.
